feat: готов проект спринта 6
DenniKs/java-kanban pull request #1
Opened 2024-06-02 21:32 UTC by DenniKs

2024-06-03 08:10 UTC, LexLippi requested changes
Привет!

Отличная работа!

Есть пара небольших замечаний, которые надо исправить!

Желаю удачи!

2024-06-03 08:10 UTC, LexLippi commented on src/ru/yandex/javacourse/kanban/manager/InMemoryHistoryManager.java
> +    public static class Node<T> {
Этот класс не должен быть публичным, снаружи данного класса мы не должны знать о его существовании

2024-06-03 08:10 UTC, LexLippi commented on src/test/ru/yandex/javacourse/kanban/manager/TestInMemoryTaskManager.java
> +    private SubTask subTask2;
Нет необходимости в модификаторах доступа в тестовых классах

2024-06-03 08:10 UTC, LexLippi commented on src/test/ru/yandex/javacourse/kanban/manager/TestSubTaskController.java
> +    private SubTask subTask2;
Аналогично тому, что писал ранее

2024-06-03 08:10 UTC, LexLippi commented on src/test/ru/yandex/javacourse/kanban/manager/TestSubTaskController.java
> +//    }
Это почему закомментировано?
Стоит либо оставить, либо удалить совсем

2024-06-03 08:59 UTC, DenniKs commented on src/test/ru/yandex/javacourse/kanban/manager/TestInMemoryTaskManager.java
> +    private SubTask subTask2;
Поправил.

2024-06-03 08:59 UTC, DenniKs commented on src/test/ru/yandex/javacourse/kanban/manager/TestSubTaskController.java
> +    private SubTask subTask2;
Поправил.

2024-06-03 09:00 UTC, DenniKs commented on src/test/ru/yandex/javacourse/kanban/manager/TestSubTaskController.java
> +//    }
Удалил.

2024-06-03 09:03 UTC, DenniKs commented
Внесены правки согласно комментариев ревью.

2024-06-04 07:36 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2024-06-05 02:07 UTC, merged