feat: готов проект спринта 7
DenniKs/java-kanban pull request #2
Opened 2024-06-21 15:38 UTC by DenniKs

Привет!
Отправляю на проверку проект спринта 7.

2024-06-22 15:57 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-06-22 15:57 UTC, LexLippi commented on src/ru/yandex/javacourse/kanban/manager/FileBackedTaskManager.java
> +    public static File tasksStorage = new File("save.csv");
Необходим конструктор, который будет принимать в качестве аргумента файл

2024-06-22 15:57 UTC, LexLippi commented on src/ru/yandex/javacourse/kanban/manager/InMemoryTaskManager.java
> +    public static HistoryManager historyManager = Managers.getDefaultHistory();
Эти поля не должны быть статическими, иначе мы не сможем создать несколько экземпляров менеджера задач

2024-06-22 15:57 UTC, LexLippi commented on src/ru/yandex/javacourse/kanban/manager/FileBackedTaskManager.java
> +                } else if (readHistory) {
1. Условия можно поменять местами
2. Тогда не будет необходимости в операторе `else`:

```java
if (readHistory) {
    break;
}
if (line.isBlank()) {
    readHistory = true;
    continue;
}
// rest part of code
```

2024-06-22 15:57 UTC, LexLippi commented on src/ru/yandex/javacourse/kanban/manager/FileBackedTaskManager.java
> +                        taskController.getTasks().put(id,
В статическом методе мы не должны работать с полями класса, более того, ты создал переменную типа `fileBackedTasksManager`, а изменяешь состояние другого менеджера

2024-06-22 15:57 UTC, LexLippi commented on src/ru/yandex/javacourse/kanban/manager/FileBackedTaskManager.java
> +                    if (type == TASK) {
Лучше использовать `switch`

2024-06-25 16:41 UTC, DenniKs commented
Привет!
Отправляю на проверку исправления после ревьюю

2024-06-26 06:28 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаюудачи в следующих спринтах!

2024-06-26 07:47 UTC, merged