feat: готов проект спринта 8
DenniKs/java-kanban pull request #3
Opened 2024-06-30 16:10 UTC by DenniKs

2024-07-01 08:13 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-07-01 08:13 UTC, LexLippi commented on src/ru/yandex/javacourse/kanban/manager/InMemoryTaskManager.java
> +        } else {
`else` не нужен, так как ты делаешь `return` в ветке условного оператора. Достаточно этого:

```java

        if (isTimeSlotAvailable(task)) {
            prioritizedTasks.add(task);
            return taskController.add(task);
        }
        throw new IllegalArgumentException("Временной интервал запроса совпадает с существующей задачей");
```

2024-07-01 08:13 UTC, LexLippi commented on src/ru/yandex/javacourse/kanban/manager/InMemoryTaskManager.java
> +                boolean overlap = newStart.isBefore(taskEnd) && newEnd.isAfter(taskStart);
Это условие не единственный возможный вариант пересечения временных отрезков, более того, они могут пересекаться, а данное условие не выполняться, надо сделать это условие необходимым и достаточным для проверки на пересечение временных отрезков

2024-07-01 08:13 UTC, LexLippi commented on src/ru/yandex/javacourse/kanban/tasks/Epic.java
> +    private void updateDurationAndTime() {
Этот метод надо вызывать при каждом добавлении или удалении подзадачи, не увидел, где это происходит

2024-07-01 12:19 UTC, DenniKs commented
Добрый день!
Внесены правки по ревью.

2024-07-02 07:52 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2024-07-02 08:29 UTC, merged