feat: проект спринта 9
DenniKs/java-kanban pull request #4
Opened 2024-07-09 18:17 UTC by DenniKs

2024-07-09 18:18 UTC, DenniKs commented
Привет!
Направляю проект спринта 9

2024-07-10 09:35 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть пара мелких замечаний, которые необходимо исправить!

Желаю удачи!

2024-07-10 09:35 UTC, LexLippi commented on src/ru/yandex/javacourse/kanban/manager/SubTaskController.java
> +        } else {
можно инвертировать условный оператор и тогда ветка `else` не понадобится, так как ты делаешь `return`

2024-07-10 09:35 UTC, LexLippi commented on src/ru/yandex/javacourse/kanban/manager/SubTaskController.java
> +            epicController.epics.get(subTask.getEpicID()).addSubTask(/*newSubTask.getId(),*/ newSubTask);
Комментарий стоит удалить

2024-07-10 09:35 UTC, LexLippi commented on src/ru/yandex/javacourse/kanban/manager/HTTPTaskManager.java
> +                List<Epic> epicList = epicController.findAll();
Вот это не очень эффективно, так как мы вынуждены обработать снова все восстановленные задачи, а мы на самом деле уже знаем пустой ли этот список или нет, так как мы восстанавливали данные

2024-07-10 09:35 UTC, LexLippi commented on src/ru/yandex/javacourse/kanban/manager/HTTPTaskManager.java
> +                }
Здесь не очень ясен порядок обхода, почему именно в таком формате мы осуществляем поиск по идентификатору

2024-07-10 19:12 UTC, DenniKs commented
Привет!
Внес корректировки согласно комментариев.

2024-07-11 14:17 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2024-07-11 14:27 UTC, merged